import type { KanbanBoard, KanbanColumn } from '../models/kanbanBoard'
import type { TaskItem } from '../models/task'

export const KANBAN_SEED_VERSION = '1'

// Due dates for the Administrator's tasks are relative to the first load, so
// the dashboard's Overdue / Due this week tiles stay populated whenever the
// app is opened. Stored the same way the task form stores a picked date.
function daysFromToday(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return new Date(`${date.getFullYear()}-${month}-${day}`).toISOString()
}

export const SEEDED_BOARDS: KanbanBoard[] = [
  {
    id: 'board-project-1',
    projectId: 'project-1',
    name: 'Task Management App Board',
  },
  {
    id: 'board-project-2',
    projectId: 'project-2',
    name: 'Mobile App Board',
  },
]

export const SEEDED_COLUMNS: KanbanColumn[] = [
  {
    id: 'col-todo',
    boardId: 'board-project-1',
    name: 'To Do',
    order: 0,
    isVisible: true,
    isDone: false,
  },
  {
    id: 'col-in-progress',
    boardId: 'board-project-1',
    name: 'In Progress',
    order: 1,
    isVisible: true,
    isDone: false,
  },
  {
    id: 'col-done',
    boardId: 'board-project-1',
    name: 'Done',
    order: 2,
    isVisible: true,
    isDone: true,
  },
  {
    id: 'col-backlog',
    boardId: 'board-project-1',
    name: 'Backlog',
    order: 3,
    isVisible: false,
    isDone: false,
  },
  {
    id: 'col-in-review',
    boardId: 'board-project-1',
    name: 'In Review',
    order: 4,
    isVisible: false,
    isDone: false,
  },
  // ---- Project 2: Mobile App ----
  {
    id: 'col-p2-todo',
    boardId: 'board-project-2',
    name: 'To Do',
    order: 0,
    isVisible: true,
    isDone: false,
  },
  {
    id: 'col-p2-in-progress',
    boardId: 'board-project-2',
    name: 'In Progress',
    order: 1,
    isVisible: true,
    isDone: false,
  },
  {
    id: 'col-p2-done',
    boardId: 'board-project-2',
    name: 'Done',
    order: 2,
    isVisible: true,
    isDone: true,
  },
]

export const SEEDED_TASKS: TaskItem[] = [
  // John Smith (seed-2)
  {
    id: 'task-1',
    columnId: 'col-todo',
    title: 'Design homepage mockup',
    description: 'Create the initial homepage layout in Figma.',
    priority: 'Medium',
    dueDate: '2026-09-23',
    assigneeId: 'seed-2',
    createdById: 'seed-3',
    isFavorite: false,
    order: 0,
    createdAt: '2026-09-10T12:00:00.000Z',
    updatedAt: '2026-09-10T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-2',
    columnId: 'col-in-progress',
    title: 'Fix login validation bug',
    description: 'Password field accepts empty input.',
    priority: 'High',
    dueDate: '2026-09-10',
    assigneeId: 'seed-2',
    createdById: 'seed-2',
    isFavorite: true,
    order: 0,
    createdAt: '2026-09-05T12:00:00.000Z',
    updatedAt: '2026-09-05T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-3',
    columnId: 'col-done',
    title: 'Project charter approved',
    description: 'Signed off by stakeholders.',
    priority: 'Medium',
    dueDate: null,
    assigneeId: 'seed-2',
    createdById: 'seed-1',
    isFavorite: false,
    order: 0,
    createdAt: '2026-09-01T12:00:00.000Z',
    updatedAt: '2026-09-05T12:00:00.000Z',
    completedAt: '2026-09-05T12:00:00.000Z',
  },
  // Jane Doe (seed-1)
  {
    id: 'task-4',
    columnId: 'col-todo',
    title: 'Update user personas',
    description: 'Refresh personas with latest research.',
    priority: 'Medium',
    dueDate: '2026-10-05',
    assigneeId: 'seed-1',
    createdById: 'seed-1',
    isFavorite: false,
    order: 1,
    createdAt: '2026-09-08T12:00:00.000Z',
    updatedAt: '2026-09-08T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-5',
    columnId: 'col-in-progress',
    title: 'Review pull request #42',
    description: 'Code review for the auth refactor.',
    priority: 'High',
    dueDate: '2026-09-24',
    assigneeId: 'seed-1',
    createdById: 'seed-3',
    isFavorite: true,
    order: 1,
    createdAt: '2026-09-15T12:00:00.000Z',
    updatedAt: '2026-09-15T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-6',
    columnId: 'col-done',
    title: 'Wireframe settings page',
    description: 'Low-fidelity wireframe for settings.',
    priority: 'Low',
    dueDate: null,
    assigneeId: 'seed-1',
    createdById: 'seed-1',
    isFavorite: false,
    order: 1,
    createdAt: '2026-08-28T12:00:00.000Z',
    updatedAt: '2026-09-03T12:00:00.000Z',
    completedAt: '2026-09-03T12:00:00.000Z',
  },
  {
    id: 'task-7',
    columnId: 'col-todo',
    title: 'Research competitor pricing',
    description: 'Compare pricing tiers of 3 competitors.',
    priority: 'High',
    dueDate: '2026-10-10',
    assigneeId: 'seed-3',
    createdById: 'seed-3',
    isFavorite: false,
    order: 2,
    createdAt: '2026-09-12T12:00:00.000Z',
    updatedAt: '2026-09-12T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-8',
    columnId: 'col-todo',
    title: 'Draft onboarding emails',
    description: 'Write the 3-part onboarding email sequence.',
    priority: 'Low',
    dueDate: '2026-10-08',
    assigneeId: 'seed-3',
    createdById: 'seed-3',
    isFavorite: false,
    order: 3,
    createdAt: '2026-09-12T12:00:00.000Z',
    updatedAt: '2026-09-12T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-9',
    columnId: 'col-in-progress',
    title: 'Write API documentation',
    description: 'Document the tasks and boards endpoints.',
    priority: 'Medium',
    dueDate: '2026-10-15',
    assigneeId: 'seed-3',
    createdById: 'seed-2',
    isFavorite: false,
    order: 2,
    createdAt: '2026-09-14T12:00:00.000Z',
    updatedAt: '2026-09-14T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-10',
    columnId: 'col-done',
    title: 'Set up repo & branching',
    description: 'Initialize repo with branch protection rules.',
    priority: 'Low',
    dueDate: null,
    assigneeId: 'seed-3',
    createdById: 'seed-3',
    isFavorite: false,
    order: 2,
    createdAt: '2026-08-20T12:00:00.000Z',
    updatedAt: '2026-09-06T12:00:00.000Z',
    completedAt: '2026-09-06T12:00:00.000Z',
  },
  // Unassigned
  {
    id: 'task-11',
    columnId: 'col-todo',
    title: 'Set up analytics dashboard',
    description: 'Evaluate and wire up a basic product analytics tool.',
    priority: 'Medium',
    dueDate: '2026-10-12',
    assigneeId: null,
    createdById: 'seed-3',
    isFavorite: false,
    order: 4,
    createdAt: '2026-09-16T12:00:00.000Z',
    updatedAt: '2026-09-16T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-12',
    columnId: 'col-in-progress',
    title: 'Investigate deployment pipeline',
    description: 'Compare CI/CD options for the Phase 3 backend rollout.',
    priority: 'Low',
    dueDate: null,
    assigneeId: null,
    createdById: 'seed-1',
    isFavorite: false,
    order: 3,
    createdAt: '2026-09-17T12:00:00.000Z',
    updatedAt: '2026-09-17T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-13',
    columnId: 'col-done',
    title: 'Initialize the Task Management App project',
    description: 'Initialize the React TypeScript project using Vite',
    priority: 'High',
    dueDate: null,
    assigneeId: 'seed-4',
    createdById: 'seed-1',
    isFavorite: false,
    order: 3,
    createdAt: '2026-09-18T12:00:00.000Z',
    updatedAt: '2026-09-18T18:00:00.000Z',
    completedAt: '2026-09-18T18:00:00.000Z',
  },
  // ---- Project 2: Mobile App ----
  {
    id: 'task-14',
    columnId: 'col-p2-todo',
    title: 'Set up push notifications',
    description: 'Integrate push notifications for task reminders.',
    priority: 'High',
    dueDate: '2026-10-09',
    assigneeId: 'seed-2',
    createdById: 'seed-3',
    isFavorite: false,
    order: 0,
    createdAt: '2026-09-19T12:00:00.000Z',
    updatedAt: '2026-09-19T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-15',
    columnId: 'col-p2-todo',
    title: 'Design app icon',
    description: 'Create the app icon in all required sizes.',
    priority: 'Low',
    dueDate: '2026-10-14',
    assigneeId: 'seed-1',
    createdById: 'seed-1',
    isFavorite: false,
    order: 1,
    createdAt: '2026-09-19T12:00:00.000Z',
    updatedAt: '2026-09-19T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-16',
    columnId: 'col-p2-in-progress',
    title: 'Build offline task sync',
    description: 'Cache tasks locally and sync when back online.',
    priority: 'Medium',
    dueDate: '2026-10-20',
    assigneeId: 'seed-3',
    createdById: 'seed-3',
    isFavorite: false,
    order: 0,
    createdAt: '2026-09-17T12:00:00.000Z',
    updatedAt: '2026-09-17T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-17',
    columnId: 'col-p2-done',
    title: 'Choose mobile framework',
    description: 'Evaluate React Native vs. Flutter and pick one.',
    priority: 'High',
    dueDate: null,
    assigneeId: 'seed-1',
    createdById: 'seed-4',
    isFavorite: false,
    order: 0,
    createdAt: '2026-09-11T12:00:00.000Z',
    updatedAt: '2026-09-15T12:00:00.000Z',
    completedAt: '2026-09-15T12:00:00.000Z',
  },
  // ---- Administrator (seed-4) ----
  {
    id: 'task-18',
    columnId: 'col-in-progress',
    title: 'Set up CI workflow',
    description: 'Run lint, type-check and tests on every pull request.',
    priority: 'High',
    dueDate: daysFromToday(-3),
    assigneeId: 'seed-4',
    createdById: 'seed-3',
    isFavorite: true,
    order: 4,
    createdAt: '2026-09-15T12:00:00.000Z',
    updatedAt: '2026-09-20T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-19',
    columnId: 'col-todo',
    title: 'Plan next sprint scope',
    description:
      'Pick stories from the backlog and estimate them with the team.',
    priority: 'Medium',
    dueDate: daysFromToday(0),
    assigneeId: 'seed-4',
    createdById: 'seed-4',
    isFavorite: false,
    order: 5,
    createdAt: '2026-09-20T12:00:00.000Z',
    updatedAt: '2026-09-20T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-20',
    columnId: 'col-todo',
    title: 'Audit accessibility on auth pages',
    description:
      'Check keyboard navigation, labels and contrast on sign-in and sign-up.',
    priority: 'Low',
    dueDate: daysFromToday(5),
    assigneeId: 'seed-4',
    createdById: 'seed-1',
    isFavorite: false,
    order: 6,
    createdAt: '2026-09-21T12:00:00.000Z',
    updatedAt: '2026-09-21T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-21',
    columnId: 'col-p2-in-progress',
    title: 'Prepare app store listing',
    description:
      'Write the description and collect screenshots for both stores.',
    priority: 'Medium',
    dueDate: daysFromToday(12),
    assigneeId: 'seed-4',
    createdById: 'seed-3',
    isFavorite: false,
    order: 1,
    createdAt: '2026-09-18T12:00:00.000Z',
    updatedAt: '2026-09-18T12:00:00.000Z',
    completedAt: null,
  },
  {
    id: 'task-22',
    columnId: 'col-p2-todo',
    title: 'Define beta tester group',
    description: 'Shortlist internal users for the first TestFlight build.',
    priority: 'Low',
    dueDate: null,
    assigneeId: 'seed-4',
    createdById: null,
    isFavorite: false,
    order: 2,
    createdAt: '2026-09-19T12:00:00.000Z',
    updatedAt: '2026-09-19T12:00:00.000Z',
    completedAt: null,
  },
]
